In [18]:
#Seth Hensley
#801055921
#homework 2 

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report
from sklearn import datasets 
from sklearn.preprocessing import StandardScaler

In [19]:
dataset = pd.read_csv("C:\\Users\\Owner\\Desktop\\Intro to ML\\diabetes.csv")
dataset.head()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [20]:
x1 = dataset.values[:,0]
x2 = dataset.values[:,1]
x3 = dataset.values[:,2]
x4 = dataset.values[:,3]
x5 = dataset.values[:,4]
x6 = dataset.values[:,5]
x7 = dataset.values[:,6]
x8 = dataset.values[:,7]

Y = dataset.Outcome
m = len(Y)
x0 = np.zeros((m,1))
x1 =x1.reshape(m,1)
x2 =x2.reshape(m,1)
x3 =x3.reshape(m,1)
x4 =x4.reshape(m,1)
x5 =x5.reshape(m,1)
x6 =x6.reshape(m,1)
x7 =x7.reshape(m,1)
x8 =x8.reshape(m,1)


X = np.hstack((x0,x1,x2,x3,x4,x5,x6,x7,x8))

#sc = StandardScaler()
#X = sc.fit_transform(X)

X,Y

(array([[  0.   ,   6.   , 148.   , ...,  33.6  ,   0.627,  50.   ],
        [  0.   ,   1.   ,  85.   , ...,  26.6  ,   0.351,  31.   ],
        [  0.   ,   8.   , 183.   , ...,  23.3  ,   0.672,  32.   ],
        ...,
        [  0.   ,   5.   , 121.   , ...,  26.2  ,   0.245,  30.   ],
        [  0.   ,   1.   , 126.   , ...,  30.1  ,   0.349,  47.   ],
        [  0.   ,   1.   ,  93.   , ...,  30.4  ,   0.315,  23.   ]]),
 0      1
 1      0
 2      1
 3      0
 4      1
       ..
 763    0
 764    0
 765    0
 766    1
 767    0
 Name: Outcome, Length: 768, dtype: int64)

In [21]:
xTrain,xTest,yTrain,yTest = train_test_split(X,Y,test_size = .2, random_state = 20)

trainLen = len(xTrain)

sc = StandardScaler()
xTrainSTD = sc.fit_transform(xTrain)
xTestSTD = sc.fit_transform(xTest)
xTrain

array([[0.00e+00, 1.00e+00, 1.00e+02, ..., 2.53e+01, 6.58e-01, 2.80e+01],
       [0.00e+00, 3.00e+00, 1.91e+02, ..., 3.09e+01, 2.99e-01, 3.40e+01],
       [0.00e+00, 3.00e+00, 7.80e+01, ..., 3.25e+01, 2.70e-01, 3.90e+01],
       ...,
       [0.00e+00, 2.00e+00, 1.08e+02, ..., 2.52e+01, 1.28e-01, 2.10e+01],
       [0.00e+00, 4.00e+00, 1.14e+02, ..., 2.89e+01, 1.26e-01, 2.40e+01],
       [0.00e+00, 9.00e+00, 1.65e+02, ..., 3.04e+01, 3.02e-01, 4.90e+01]])

In [43]:
C = [.1]
for c in C:
    clf = LogisticRegression(penalty = 'l1', C=c, solver = 'liblinear')
    clf.fit(xTrain, yTrain)
    print('c:', c)
    print( 'Training accuracy:', clf.score(xTrainSTD,yTrain))
    print('test accuracy:', clf.score(xTestSTD,yTest))
    print('')

c: 0.1
Training accuracy: 0.6498371335504886
test accuracy: 0.6558441558441559



In [44]:
test_size=.2 
seed =0
xtr, xt,ytr,yt = train_test_split(X,Y,test_size=test_size,random_state = seed)
model = LogisticRegression(solver='liblinear')
model.fit(xtr,ytr)
predicted = model.predict(xt)
matrix = confusion_matrix(yt, predicted)
print(matrix)

[[98  9]
 [19 28]]


In [45]:
model = LogisticRegression(solver='liblinear')
model.fit(xTrainSTD,yTrain)
predicted = model.predict(xTestSTD)
report = classification_report(yTest,predicted)
print(report)

              precision    recall  f1-score   support

           0       0.78      0.89      0.83       101
           1       0.72      0.53      0.61        53

    accuracy                           0.77       154
   macro avg       0.75      0.71      0.72       154
weighted avg       0.76      0.77      0.76       154

