In [1]:
#Seth Hensley
#801055921
#homework 2 

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report
from sklearn import datasets 
from sklearn.preprocessing import StandardScaler

dataset = pd.read_csv("C:\\Users\\Owner\\Desktop\\Intro to ML\\diabetes.csv")
dataset.head()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [2]:
x1 = dataset.values[:,0]
x2 = dataset.values[:,1]
x3 = dataset.values[:,2]
x4 = dataset.values[:,3]
x5 = dataset.values[:,4]
x6 = dataset.values[:,5]
x7 = dataset.values[:,6]
x8 = dataset.values[:,7]

Y = dataset.Outcome
m = len(Y)
x0 = np.zeros((m,1))
x1 =x1.reshape(m,1)
x2 =x2.reshape(m,1)
x3 =x3.reshape(m,1)
x4 =x4.reshape(m,1)
x5 =x5.reshape(m,1)
x6 =x6.reshape(m,1)
x7 =x7.reshape(m,1)
x8 =x8.reshape(m,1)


X = np.hstack((x0,x1,x2,x3,x4,x5,x6,x7,x8))

X,Y

(array([[  0.   ,   6.   , 148.   , ...,  33.6  ,   0.627,  50.   ],
        [  0.   ,   1.   ,  85.   , ...,  26.6  ,   0.351,  31.   ],
        [  0.   ,   8.   , 183.   , ...,  23.3  ,   0.672,  32.   ],
        ...,
        [  0.   ,   5.   , 121.   , ...,  26.2  ,   0.245,  30.   ],
        [  0.   ,   1.   , 126.   , ...,  30.1  ,   0.349,  47.   ],
        [  0.   ,   1.   ,  93.   , ...,  30.4  ,   0.315,  23.   ]]),
 0      1
 1      0
 2      1
 3      0
 4      1
       ..
 763    0
 764    0
 765    0
 766    1
 767    0
 Name: Outcome, Length: 768, dtype: int64)

In [4]:
xTrain,xTest,yTrain,yTest = train_test_split(X,Y,test_size = .2, random_state = 20)

trainLen = len(xTrain)

sc = StandardScaler()
xTrainSTD = sc.fit_transform(xTrain)
xTestSTD = sc.fit_transform(xTest)
xTrainSTD

array([[ 0.        , -0.84466975, -0.65217248, ..., -0.85828111,
         0.5366396 , -0.43171756],
       [ 0.        , -0.25059503,  2.23343769, ..., -0.13869032,
        -0.53398763,  0.08265744],
       [ 0.        , -0.25059503, -1.34979252, ...,  0.06690704,
        -0.62047284,  0.51130327],
       ...,
       [ 0.        , -0.54763239, -0.39849247, ..., -0.87113094,
        -1.04395213, -1.03182173],
       [ 0.        ,  0.04644232, -0.20823246, ..., -0.39568703,
        -1.04991662, -0.77463423],
       [ 0.        ,  1.53162911,  1.40897764, ..., -0.2029395 ,
        -0.52504088,  1.36859494]])

In [14]:
C = [.1]
for c in C:
    clf = LogisticRegression(penalty = 'l1', C=c, solver = 'liblinear')
    clf.fit(xTrain, yTrain)
    print('c:', c)
    print( 'Training accuracy:', clf.score(xTrainSTD,yTrain))
    print('test accuracy:', clf.score(xTestSTD,yTest))
    print('')
    

c: 0.1
Training accuracy: 0.6498371335504886
test accuracy: 0.6558441558441559



In [15]:
kfold = KFold(n_splits = 5 , random_state = 0, shuffle= True)
model = LogisticRegression(solver = 'liblinear')
results = cross_val_score(model, xTrainSTD,yTrain, cv=kfold)

print("accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100))



accuracy: 77.848% (1.441%)


In [16]:
kfold = KFold(n_splits = 10 , random_state = 0, shuffle= True)
model = LogisticRegression(solver = 'liblinear')
results = cross_val_score(model, xTrainSTD,yTrain, cv=kfold)

print("accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100))



accuracy: 77.858% (2.358%)


In [18]:
model = LogisticRegression(solver='liblinear')
model.fit(xTrainSTD,yTrain)
predicted = model.predict(xTestSTD)
matrix = confusion_matrix(yTest, predicted)
print(matrix)

[[90 11]
 [25 28]]


In [19]:
model = LogisticRegression(solver='liblinear')
model.fit(xTrainSTD,yTrain)
predicted = model.predict(xTestSTD)
report = classification_report(yTest,predicted)
print(report)

              precision    recall  f1-score   support

           0       0.78      0.89      0.83       101
           1       0.72      0.53      0.61        53

    accuracy                           0.77       154
   macro avg       0.75      0.71      0.72       154
weighted avg       0.76      0.77      0.76       154

