In [2]:
#Seth Hensley
#801055921
#homework 5 problem 2a

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

from matplotlib import pyplot as plt
%matplotlib inline
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report
from sklearn import datasets 
from sklearn.preprocessing import StandardScaler

dataset = pd.read_csv("C:\\Users\\shens\\Desktop\\Housing.csv")
dataset

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [3]:
x1 = dataset.values[:,1]
x2 = dataset.values[:,2]
x3 = dataset.values[:,3]
x4 = dataset.values[:,4]
x5 = dataset.values[:,10]
y = dataset.values[:,0]


m = len(y)
b = torch.zeros(())
x1 =x1.reshape(m,1)
x2 =x2.reshape(m,1)
x3 =x3.reshape(m,1)
x4 =x4.reshape(m,1)
x5 =x5.reshape(m,1)

y=y.reshape(m,1)

x = np.hstack((x1,x2,x3,x4,x5))


newDataset = np.hstack((y,x))
newDataset

array([[13300000, 7420, 4, 2, 3, 2],
       [12250000, 8960, 4, 4, 4, 3],
       [12250000, 9960, 3, 2, 2, 2],
       ...,
       [1750000, 3620, 2, 1, 1, 0],
       [1750000, 2910, 3, 1, 1, 0],
       [1750000, 3850, 3, 1, 2, 0]], dtype=object)

In [4]:
sc = StandardScaler()
standardData = sc.fit_transform(newDataset)
standardData

array([[ 4.56636513,  1.04672629,  1.40341936,  1.42181174,  1.37821692,
         1.51769249],
       [ 4.00448405,  1.75700953,  1.40341936,  5.40580863,  2.53202371,
         2.67940935],
       [ 4.00448405,  2.21823241,  0.04727831,  1.42181174,  0.22441013,
         1.51769249],
       ...,
       [-1.61432675, -0.70592066, -1.30886273, -0.57018671, -0.92939666,
        -0.80574124],
       [-1.61432675, -1.03338891,  0.04727831, -0.57018671, -0.92939666,
        -0.80574124],
       [-1.61432675, -0.5998394 ,  0.04727831, -0.57018671,  0.22441013,
        -0.80574124]])

In [5]:
Y = standardData[:,0]
X1 = standardData[:,1]
X2 = standardData[:,2]
X3 = standardData[:,3]
X4 = standardData[:,4]
X5 = standardData[:,5]

X1=X1.reshape(m,1)
X2=X2.reshape(m,1)
X3=X3.reshape(m,1)
X4=X4.reshape(m,1)
X5=X5.reshape(m,1)
b=np.zeros((m,1))


Y=Y.reshape(m,1)
X= np.hstack((X1,X2,X3,X4,X5,b))


#X=np.hstack((X,b))

#X,Y

In [6]:
xtrain, xtest, ytrain, ytest = train_test_split(X,Y,test_size = .2, random_state = 20)


w1=torch.ones(())
w2=torch.ones(())
w3=torch.ones(())
w4=torch.ones(())
w5=torch.ones(())


w = np.hstack((w1,w2,w3,w4,w5))

#xtrain,xtest

In [7]:
def model(x,w1,w2,w3,w4,w5):
    return x[:,0]*w1+x[:,1]*w2+x[:,2]*w3+x[:,3]*w4+x[:,4]*w5+x[:,5]

In [8]:
def loss_fn(t_p, t_c):
    squared_diffs = (t_p - t_c)**2
    return squared_diffs.mean()

def dloss_fn(t_p, t_c):
    dsq_diffs=2* (t_p - t_c) / t_p.size(0)
    return dsq_diffs

def dmodel_dw1(t_u, w1, w2, b):
    return t_u[:,0]

def dmodel_dw2(t_u, w1, w2, b):
    return t_u[:,1]

def dmodel_dw3(t_u, w1, w2, b):
    return t_u[:,2]

def dmodel_dw4(t_u, w1, w2, b):
    return t_u[:,3]

def dmodel_dw5(t_u, w1, w2, b):
    return t_u[:,4]

def dmodel_db(t_u,w1,w2,b):
    return 1

In [9]:
def grad_fn(t_u, t_c, t_p, w1, w2, w3,w4,w5, b):
    dloss_dtp = dloss_fn(t_p, t_c)
    dloss_dw1 = dloss_dtp * dmodel_dw1(t_u, w1,w2, b)
    dloss_dw2 = dloss_dtp * dmodel_dw2(t_u,w1,w2,b)
    dloss_dw3 = dloss_dtp * dmodel_dw2(t_u,w1,w2,b)
    dloss_dw4 = dloss_dtp * dmodel_dw2(t_u,w1,w2,b)
    dloss_dw5 = dloss_dtp * dmodel_dw2(t_u,w1,w2,b)
    dloss_db = dloss_dtp * dmodel_db(t_u, w1,w2, b)
    return torch.stack([dloss_dw1.sum(), dloss_dw2.sum(), dloss_dw3.sum(), dloss_dw4.sum(), dloss_dw5.sum(),dloss_db.sum()])

In [10]:
def training_loop(n_epochs, learning_rate, params, t_u, t_c):
    for epoch in range(1, n_epochs + 1):
        w1, w2, w3, w4, w5, b = params
        t_p = model(t_u, w1,w2,w3,w4,w5)
        loss = loss_fn(t_p, t_c)
        grad = grad_fn(t_u, t_c, t_p, w1, w2, w3, w4, w5, b)
        params = params - learning_rate * grad
        if epoch%500==0:
            print('Epoch %d, Loss %f' % (epoch, float(loss)))
    return params

In [15]:
xtrainT = torch.from_numpy(xtrain)


training_loop(n_epochs = 5000, learning_rate = .00000001, params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0]), t_u = xtrainT, t_c = ytrain)


Epoch 500, Loss 10.223083
Epoch 1000, Loss 10.065888
Epoch 1500, Loss 9.911372
Epoch 2000, Loss 9.759491
Epoch 2500, Loss 9.610199
Epoch 3000, Loss 9.463453
Epoch 3500, Loss 9.319207
Epoch 4000, Loss 9.177421
Epoch 4500, Loss 9.038052
Epoch 5000, Loss 8.901058


tensor([0.9254, 0.9160, 0.9160, 0.9160, 0.9160, 0.0010], dtype=torch.float64)

In [16]:
training_loop(n_epochs = 5000, learning_rate = .0000001, params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0]), t_u = xtrainT, t_c = ytrain)


Epoch 500, Loss 8.903398
Epoch 1000, Loss 7.655076
Epoch 1500, Loss 6.603901
Epoch 2000, Loss 5.718696
Epoch 2500, Loss 4.973219
Epoch 3000, Loss 4.345379
Epoch 3500, Loss 3.816582
Epoch 4000, Loss 3.371178
Epoch 4500, Loss 2.995991
Epoch 5000, Loss 2.679928


tensor([0.4685, 0.4145, 0.4145, 0.4145, 0.4145, 0.0035], dtype=torch.float64)

In [17]:
training_loop(n_epochs = 5000, learning_rate = .000001, params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0]), t_u = xtrainT, t_c = ytrain)


Epoch 500, Loss 2.682909
Epoch 1000, Loss 1.292927
Epoch 1500, Loss 1.040466
Epoch 2000, Loss 0.993667
Epoch 2500, Loss 0.984631
Epoch 3000, Loss 0.982743
Epoch 3500, Loss 0.982292
Epoch 4000, Loss 0.982163
Epoch 4500, Loss 0.982118
Epoch 5000, Loss 0.982100


tensor([ 0.0038, -0.0004, -0.0004, -0.0004, -0.0004, -0.0861],
       dtype=torch.float64)

In [19]:
training_loop(n_epochs = 5000, learning_rate = .00001, params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0]), t_u = xtrainT, t_c = ytrain)


Epoch 500, Loss 0.982100
Epoch 1000, Loss 0.982085
Epoch 1500, Loss 0.982085
Epoch 2000, Loss 0.982085
Epoch 2500, Loss 0.982085
Epoch 3000, Loss 0.982085
Epoch 3500, Loss 0.982085
Epoch 4000, Loss 0.982085
Epoch 4500, Loss 0.982085
Epoch 5000, Loss 0.982085


tensor([-2.1856e-05, -4.8986e-05, -4.8986e-05, -4.8986e-05, -4.8986e-05,
        -1.0802e+00], dtype=torch.float64)