In [1]:
#Seth Hensley
#801055921
#homework 5 
#1A


import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

from matplotlib import pyplot as plt
%matplotlib inline
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.set_printoptions(edgeitems=2)
torch.manual_seed(123)

In [2]:
#1B

In [3]:
t_c = [0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = torch.tensor(t_c)
t_u = torch.tensor(t_u)


In [4]:
def model(t_u, w1, w2, b):
    return w2 * t_u**2 + w1*t_u + b

In [5]:
def loss_fn(t_p, t_c):
    squared_diffs = (t_p - t_c)**2
    return squared_diffs.mean()

def dmodel_dw1(t_u, w1, w2, b):
    return t_u

def dmodel_dw2(t_u, w1, w2, b):
    return t_u**2

def dmodel_db(t_u,w1,w2,b):
    return 1

    

In [6]:
def dloss_fn(t_p, t_c):
    dsq_diffs=2* (t_p - t_c) / t_p.size(0)
    return dsq_diffs

In [7]:
def grad_fn(t_u, t_c, t_p, w1, w2, b):
    dloss_dtp = dloss_fn(t_p, t_c)
    dloss_dw1 = dloss_dtp * dmodel_dw1(t_u, w1,w2, b)
    dloss_dw2 = dloss_dtp * dmodel_dw2(t_u,w1,w2,b)
    dloss_db = dloss_dtp * dmodel_db(t_u, w1,w2, b)
    return torch.stack([dloss_dw1.sum(), dloss_dw2.sum(), dloss_db.sum()])

In [8]:
def training_loop(n_epochs, learning_rate, params, t_u, t_c):
    for epoch in range(1, n_epochs + 1):
        w1, w2, b = params
        t_p = model(t_u, w1,w2, b)
        loss = loss_fn(t_p, t_c)
        grad = grad_fn(t_u, t_c, t_p, w1, w2, b)
        params = params - learning_rate * grad
        if epoch%500==0:
            print('Epoch %d, Loss %f' % (epoch, float(loss)))
    return params

In [12]:
training_loop(n_epochs = 5000, learning_rate = .00001, params = torch.tensor([1.0, 1.0, 0.0]), t_u = t_u, t_c = t_c)

Epoch 500, Loss nan
Epoch 1000, Loss nan
Epoch 1500, Loss nan
Epoch 2000, Loss nan
Epoch 2500, Loss nan
Epoch 3000, Loss nan
Epoch 3500, Loss nan
Epoch 4000, Loss nan
Epoch 4500, Loss nan
Epoch 5000, Loss nan


tensor([nan, nan, nan])

In [13]:
training_loop(n_epochs = 5000, learning_rate = .000001, params = torch.tensor([1.0, 1.0, 0.0]), t_u = t_u, t_c = t_c)


Epoch 500, Loss nan
Epoch 1000, Loss nan
Epoch 1500, Loss nan
Epoch 2000, Loss nan
Epoch 2500, Loss nan
Epoch 3000, Loss nan
Epoch 3500, Loss nan
Epoch 4000, Loss nan
Epoch 4500, Loss nan
Epoch 5000, Loss nan


tensor([nan, nan, nan])

In [14]:
training_loop(n_epochs = 5000, learning_rate = .0000001, params = torch.tensor([1.0, 1.0, 0.0]), t_u = t_u, t_c = t_c)


Epoch 500, Loss nan
Epoch 1000, Loss nan
Epoch 1500, Loss nan
Epoch 2000, Loss nan
Epoch 2500, Loss nan
Epoch 3000, Loss nan
Epoch 3500, Loss nan
Epoch 4000, Loss nan
Epoch 4500, Loss nan
Epoch 5000, Loss nan


tensor([nan, nan, nan])

In [17]:
training_loop(n_epochs = 5000, learning_rate = .000000001, params = torch.tensor([1.0, 1.0, 0.0]), t_u = t_u, t_c = t_c)


Epoch 500, Loss 204.073151
Epoch 1000, Loss 204.009766
Epoch 1500, Loss 203.947495
Epoch 2000, Loss 203.885147
Epoch 2500, Loss 203.822845
Epoch 3000, Loss 203.760559
Epoch 3500, Loss 203.698227
Epoch 4000, Loss 203.636002
Epoch 4500, Loss 203.573685
Epoch 5000, Loss 203.511429


tensor([ 9.8242e-01, -1.1381e-02, -3.2925e-04])