In [1]:
#Seth Hensley
#801055921
#homework 4.1

import warnings
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn import metrics
from sklearn import datasets 
from sklearn.datasets import load_breast_cancer
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn import svm

In [2]:
cancerData = load_breast_cancer()
cancerX = pd.DataFrame(cancerData.data)
cancerY = pd.DataFrame(cancerData.target)

#cancerX,cancerY

sc = StandardScaler()
cancerXSTD = sc.fit_transform(cancerX)
cancerXSTD#cancerY.shape

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [3]:
N= 25
for i in range(1,25):
    print('principle component(s)=' ,i)
    pca = PCA(n_components = i)
    principalComponents = pca.fit_transform(cancerXSTD)
    principalDF = pd.DataFrame(data = principalComponents)

    principalDF

    xTrain,xTest,yTrain,yTest = train_test_split(principalDF,cancerY,test_size = .2, random_state = 20)

    C = [.1]
    for c in C:
        clf = LogisticRegression(penalty = 'l1', C=c, solver = 'liblinear')
        clf.fit(xTrain, yTrain)
        print('c:', c)
        print( 'Training accuracy:', clf.score(xTrain,yTrain))
        print('test accuracy:', clf.score(xTest,yTest))
        print('')
    warnings.filterwarnings('ignore')


    predicted = clf.predict(xTest)
    matrix = confusion_matrix(yTest,predicted)
    print(matrix)


    report = classification_report(yTest,predicted)
    print(report)

principle component(s)= 1
c: 0.1
Training accuracy: 0.9208791208791208
test accuracy: 0.9122807017543859

[[42  6]
 [ 4 62]]
              precision    recall  f1-score   support

           0       0.91      0.88      0.89        48
           1       0.91      0.94      0.93        66

    accuracy                           0.91       114
   macro avg       0.91      0.91      0.91       114
weighted avg       0.91      0.91      0.91       114

principle component(s)= 2
c: 0.1
Training accuracy: 0.9516483516483516
test accuracy: 0.9824561403508771

[[47  1]
 [ 1 65]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98        48
           1       0.98      0.98      0.98        66

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114

principle component(s)= 3
c: 0.1
Training accuracy: 0.9494505494505494
test accuracy: 0.97368421

C:\Users\Owner\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[47  1]
 [ 0 66]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        48
           1       0.99      1.00      0.99        66

    accuracy                           0.99       114
   macro avg       0.99      0.99      0.99       114
weighted avg       0.99      0.99      0.99       114

principle component(s)= 11
c: 0.1
Training accuracy: 0.9648351648351648
test accuracy: 0.9912280701754386

[[47  1]
 [ 0 66]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        48
           1       0.99      1.00      0.99        66

    accuracy                           0.99       114
   macro avg       0.99      0.99      0.99       114
weighted avg       0.99      0.99      0.99       114

principle component(s)= 12
c: 0.1
Training accuracy: 0.9648351648351648
test accuracy: 0.9912280701754386

[[47  1]
 [ 0 66]]
              precision    recall  f1-score   support

           0       1

In [4]:
#it appears that after the number of principle componenets exceeds 5 the result from regression training do not improve
# 5 principle components will be used 

In [5]:
pca = PCA(n_components = 5)
principalComponents = pca.fit_transform(cancerXSTD)
principalDF = pd.DataFrame(data = principalComponents)

xTrain,xTest,yTrain,yTest = train_test_split(principalDF,cancerY,test_size = .2, random_state = 20)

In [6]:
clf = svm.SVC(kernel = 'linear',C=1E6)
clf.fit(xTrain,yTrain)
predictedSVM = clf.predict(xTest)

cfLinear = confusion_matrix(yTest,predictedSVM)
reportLinear = classification_report(yTest,predictedSVM)
print(cfLinear)
print(reportLinear)
print('test accuracy', metrics.accuracy_score(yTest,predictedSVM))

[[45  3]
 [ 0 66]]
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        48
           1       0.96      1.00      0.98        66

    accuracy                           0.97       114
   macro avg       0.98      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

test accuracy 0.9736842105263158


In [7]:
#for 5 principle components there is not much of a diffrence in 
#precision recall or accuracy. for lower numbers of principle components 
#the precision and recall are improved however the overall
#test accuracy stays about the same. 
#for a lower amount of principle components a linear kernel worked best

In [8]:
clf = svm.SVC(kernel = 'poly',C=1E6)
clf.fit(xTrain,yTrain)
predictedSVM = clf.predict(xTest)

cfLinear = confusion_matrix(yTest,predictedSVM)
reportLinear = classification_report(yTest,predictedSVM)
print(cfLinear)
print(reportLinear)
print('test accuracy', metrics.accuracy_score(yTest,predictedSVM))

[[44  4]
 [ 5 61]]
              precision    recall  f1-score   support

           0       0.90      0.92      0.91        48
           1       0.94      0.92      0.93        66

    accuracy                           0.92       114
   macro avg       0.92      0.92      0.92       114
weighted avg       0.92      0.92      0.92       114

test accuracy 0.9210526315789473


In [9]:
clf = svm.SVC(kernel = 'rbf',C=1E6)
clf.fit(xTrain,yTrain)
predictedSVM = clf.predict(xTest)

cfLinear = confusion_matrix(yTest,predictedSVM)
reportLinear = classification_report(yTest,predictedSVM)
print(cfLinear)
print(reportLinear)
print('test accuracy', metrics.accuracy_score(yTest,predictedSVM))

[[43  5]
 [ 5 61]]
              precision    recall  f1-score   support

           0       0.90      0.90      0.90        48
           1       0.92      0.92      0.92        66

    accuracy                           0.91       114
   macro avg       0.91      0.91      0.91       114
weighted avg       0.91      0.91      0.91       114

test accuracy 0.9122807017543859


In [10]:
clf = svm.SVC(kernel = 'sigmoid',C=1E6)
clf.fit(xTrain,yTrain)
predictedSVM = clf.predict(xTest)

cfLinear = confusion_matrix(yTest,predictedSVM)
reportLinear = classification_report(yTest,predictedSVM)
print(cfLinear)
print(reportLinear)
print('test accuracy', metrics.accuracy_score(yTest,predictedSVM))

[[45  3]
 [ 3 63]]
              precision    recall  f1-score   support

           0       0.94      0.94      0.94        48
           1       0.95      0.95      0.95        66

    accuracy                           0.95       114
   macro avg       0.95      0.95      0.95       114
weighted avg       0.95      0.95      0.95       114

test accuracy 0.9473684210526315


In [12]:
pca = PCA(n_components = 4)
principalComponents = pca.fit_transform(cancerXSTD)
principalDF = pd.DataFrame(data = principalComponents)

xTrain,xTest,yTrain,yTest = train_test_split(principalDF,cancerY,test_size = .2, random_state = 20)


clf = svm.SVC(kernel = 'linear')
clf.fit(xTrain,yTrain)
predictedSVM = clf.predict(xTest)

cfLinear = confusion_matrix(yTest,predictedSVM)
reportLinear = classification_report(yTest,predictedSVM)
print(cfLinear)
print(reportLinear)
print('test accuracy', metrics.accuracy_score(yTest,predictedSVM))

[[46  2]
 [ 1 65]]
              precision    recall  f1-score   support

           0       0.98      0.96      0.97        48
           1       0.97      0.98      0.98        66

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

test accuracy 0.9736842105263158


In [13]:
#it is difficult to tell if the SVM classifier made any improvements when
#compaired to homework 3 for 5 principle components.
#however for lower amounts of principle components like four(above)
#SVM did make a small diffrence in accuracy precision and recall